map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/workspace/src/navigation/maps/map_reveal_107.yaml"

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 5.0
    planner_plugins: ["AStar", "Dijkstra", "GBFS"]
    AStar:
      plugin: "navigation/SelectablePlanner"
      algorithm: "A_STAR"
    Dijkstra:
      plugin: "navigation/SelectablePlanner"
      algorithm: "Dijkstra"
    GBFS:
      plugin: "navigation/SelectablePlanner"
      algorithm: "GBFS"

global_costmap:
  global_costmap:
    ros__parameters: 
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: false
      robot_radius: 0.25
      width: 200
      height: 200
      resolution: 0.05
      origin_x: -5.0
      origin_y: -5.0
      rolling_window: false
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"] 
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        subscribe_to_updates: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: ui_pointcloud
        ui_pointcloud:
          topic: /frontend/pointcloud
          max_obstacle_height: 2.0
          clearing: false
          marking: true
          data_type: "PointCloud2"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 10.0
        inflation_radius: 0.25

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      use_sim_time: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: ui_pointcloud
        ui_pointcloud:
          topic: /frontend/pointcloud
          max_obstacle_height: 2.0
          clearing: false
          marking: true
          data_type: "PointCloud2"
          raytrace_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        cost_scaling_factor: 10.0
        inflation_radius: 0.45

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoalCritic"
      Oscillation:
        plugin: "dwb_critics::OscillationCritic"
      BaseObstacle:
        plugin: "dwb_critics::BaseObstacleCritic"
      GoalAlign:
        plugin: "dwb_critics::GoalAlignCritic"
      PathAlign:
        plugin: "dwb_critics::PathAlignCritic"
      PathDist:
        plugin: "dwb_critics::PathDistCritic"
      GoalDist:
        plugin: "dwb_critics::GoalDistCritic"